### ISSUE TITLE
Script for BERT-base training to reproduce the results

### ISSUE THREAD

**Issue by achouhan93** [RAIVNLab/MRL#17]
Hi Team! Firstly, thank you for the nice paper and approach. Secondly, while browsing through the paper of MRL, it is mentioned that the BERT-Base model was trained for MLM task on English Wikipedia and BookCorpus in Appendix C and values are provided in Table 7. However, I was not able to locate the script that trains the BERT-based model in the repository to reproduce the results. It will be really helpful if you can locate the script. Thanks in advance.

**Comment by aniketrege** [comment]
Hello, the BERT-Base model from the original MRL work was trained internally at Google and is not open sourced. We can provide BERT-Base models trained at AI2 for our followup AdANNS work (ref: [Qingqing Cao](https://github.com/csarron)) on Natural Questions with MRL, following the [DPR codebase](https://github.com/facebookresearch/DPR).

MRL-NQ models are available on [Huggingface](https://huggingface.co/aniketr/mrl-nq)
