### ISSUE TITLE
Usage of MRL in self-supervised model training

### ISSUE THREAD

**Issue by ajkailash** [RAIVNLab/MRL#18]
Thanks for the implementation. Can this method be used in the training of self-supervised vision transformer models like [DINO](https://github.com/facebookresearch/dino), [iBOT](https://github.com/bytedance/ibot), ... etc. Note, these methods involve multiple global and local crops. Along with regularization mechanisms like centering and sharpening.

**Comment by adityakusupati** [comment]
Yes. As long as you have a information bottleneck which is a dense vector, MRL should just work!
