### ISSUE TITLE
Release Code For BERT MRL

### ISSUE THREAD

**Issue by tanmaylaud** [RAIVNLab/MRL#19]
Hi @adityakusupati , 
Great work! After the reading the paper, it wasn't quite clear how you pretrained BERT with MRL. 

Could please share the code/scripts for BERT MRL? 

Thanks!

**Comment by adityakusupati** [comment]
Hi Tanmay,

Unfortunately, we do not have them in the OSS domain. However, an alternative is to use this: https://huggingface.co/nomic-ai/nomic-embed-text-v1.5 

They also have the training code here: https://github.com/nomic-ai/contrastors

Hope it helps.

**Comment by tanmaylaud** [comment]
Hi @adityakusupati , 

Thanks for the links. I went through codebase but could only find evaluation code (which is fairly straightforward). 
I wanted to know how to train the model not just for contrastive, but also MLM , with MRL. 
It would be great if you could share pseudocode/ideas.

**Comment by adityakusupati** [comment]
They do have training but for the dual encoder and not for the bert model.

For Bert MLM I don't think you need to do anything more than what we do currently in MRL. You replace the last layer with MRL layer and that should be it.

**Comment by tanmaylaud** [comment]
Interesting! I was thinking that all the FFN layers are converted to MRL in BERT. What is your thought on that ?

**Comment by adityakusupati** [comment]
FFN in all transformer layers? Then that is a task for MatFormer paper. You can check that paper out.

**Comment by tanmaylaud** [comment]
Awesome! That paper does exactly what I was talking about. Great work again!
