### ISSUE TITLE
Publish MRL as a Lightning Studio 

### ISSUE THREAD

**Issue by tchaton** [RAIVNLab/MRL#21]
Hey there,

This paper and work is awesome. I think it would be great to publish it within a Lightning Studio: https://lightning.ai/.

They are fully persistent cloud IDE that anyone can duplicate. When they do, they get dependencies, data, model checkpoints, API endpoints, servers, etc...

So everything available and ready to go in a single click.

**Comment by adityakusupati** [comment]
Sure thing. @tchaton let me know how to do it!

**Comment by tchaton** [comment]
Hey @adityakusupati. Just create an account and you get the ide for free. You can setup the project and publish to the gallery for everyone to use. It is quite easy.

**Comment by adityakusupati** [comment]
Cool, will do
