### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [RAIVNLab/MRL#5]
First, thank you for sharing this project with us!

Could you please add an explicit `LICENSE` file to the repo so that it's clear
under what terms the content is provided, and under what terms user
contributions are licensed?

Per [GitHub docs on licensing]:

> [...] without a license, the default copyright laws apply, meaning that you
> retain all rights to your source code and no one may reproduce, distribute,
> or create derivative works from your work. If you're creating an open source
> project, we strongly encourage you to include an open source license. The
> [Open Source Guide] provides additional guidance on choosing the correct
> license for your project.

Thanks!

[GitHub docs on licensing]: https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license
[Open Source Guide]: https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project

**Comment by aniketrege** [comment]
Hello, I have updated the license in #4 , closing this issue.
